CORE-1450 Update to model v5.2
cyverse-de/road-runner pull request #21
Opened 2021-06-19 02:33 UTC by psarando

This PR will update the `model` package to `v5.2`.

This was done by running the following commands, though I've not done much with Go development lately, so I'm not sure if I'm missing anything else:
```
go get -u gopkg.in/cyverse-de/model.v5
go mod tidy
go build
go test
```
```
PASS
ok  	github.com/cyverse-de/road-runner	0.035s
```

2021-06-21 21:50 UTC, slr71 requested changes
I don't think this is going to work the way it is, unfortunately. Switching to Go modules changes the import path from `gopkg.in/cyverse-de/model.v5` to `github.com/cyverse-de/model`, which will require us to change the import path. Unfortunately, that's going to require us to change other repositories as well because the import path has to be updated in other dependencies of `road-runner` that also use `model`. So far, I think that `model` and `messaging` are the only two that we'll have to update.

2021-06-21 21:52 UTC, slr71 commented
Oh, one thing I meant to mention in my review comment was that I haven't been able to find a way to get `go get` to fully update a dependency from `gopkg.in`. If we could get that to work then we could avoid sweeping changes.

2021-06-22 00:47 UTC, psarando commented on status.go
> +}
Thanks to @slr71 for this suggestion 👍

2021-06-22 00:50 UTC, slr71 approved these changes
Looks good to me! 👍 :shipit:

2021-06-22 00:51 UTC, psarando commented
Thanks for the review! 👍

2021-06-22 00:51 UTC, merged